### ISSUE TITLE
Conversion aborts with no error output

### ISSUE THREAD

**Issue by artob** [opcode-eu-org-libs/asciicast2movie#1]
This is a hugely promising, and much needed, project, but unfortunately I can't get it to work:

```bash
$ pip3 install asciicast2movie
...

$ asciicast2movie 360104.cast 360104.mp4
Killed
```

This is on Ubuntu 18.04 LTS with Python 3.6.9 and asciicast2movie 0.3.0.

The Asciinema file I'm trying to convert can be downloaded here: https://asciinema.org/a/360104.cast?dl=1

**Comment by rpaciorek** [comment]
This look like 'out of memory' problem.

How much RAM do you have? Can you check RAM consumption while run asciicast2movie script?

With default settings this asciicast file generate 545 images (frames) 2458 * 1344 pixels each and 4 byte per pixel.
This is 6.7GB raw-image data. `mpy.ImageClip( numpy.array(image) )` use 3 time more memory (I will try check why), so processing this file with default settings need 21-22GB RAM.

You can change default settings by modify 169 line of asciicast2movie.py file and st font size to 8 (this should reduce the RAM requirement to 4-5GB).
You can also split input into smaller chunks and render its independently.

**Comment by artob** [comment]
@rpaciorek This was on a 16 GB host. Thanks a bunch, that suggest (changing font size to 8) does work:

```bash
$ time asciicast2movie 360104.cast 360104.mp4
Moviepy - Building video 360104.mp4.
Moviepy - Writing video 360104.mp4

Moviepy - Done !                                                                                                                                                                                            
Moviepy - video ready 360104.mp4

real	1m42.143s
user	2m30.794s
sys	0m9.911s
```

The output is not exactly legible, though, with this font size. So, I'll need to run it on a host with more memory.

Now, ideally, `asciicast2movie` would output something more useful than "Killed" in this circumstance; but this matter is clear in any case, so I'll close the issue.

**Comment by rpaciorek** [comment]
`asciicast2movie` was ended by sigkill send by kernel (out of memory killer), so `asciicast2movie` can't react to it.
"Killed" is printing via parent (bash) based on return code from `asciicast2movie`.

In 0.3.2 I add printing info about memory usage estimation on script start and (only on Linux) warning when is more than 90% of available memory.
